### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by eiurur** [eiurur/1draw-ranking#8]
- [ ] Key binding
  - Jで次、Kで戻る、L or Fでふぁぼ、Rでリツイート、Dで画像保存、Uで新しいタブでUserページを開く
  - その説明を右下に載せる
- [x] TOPへ戻るボタンつける。それか、トグルボタンをFixedさせる。
- [x] 画像保存をダウンロードタグからFileAPIによるものに変更。
- [x] 上の変更に伴い、保存するファイル名をtweetTextに、保存先フォルダをuserNameに変更(user pageのとき、それ以外ではタグ名とする)
- [ ] Resemble.jsで類似画像判定処理を実装
- [ ] Login with Twitterは説明ページに変更(スクショ付きで、ふぁぼれます、リツイートできます、画像取得できます、タグ設定できます)。そこの最上部と最下部にLogin with Twitter ボタンを設置。

**Comment by eiurur** [comment]
ok → 76ee733a05ab40

**Comment by eiurur** [comment]
![1448631773717](https://cloud.githubusercontent.com/assets/4101830/15195811/76bb1df2-1804-11e6-89bd-b7af75c2de16.jpg)

**Comment by eiurur** [comment]
![1462524438003](https://cloud.githubusercontent.com/assets/4101830/15195816/841707cc-1804-11e6-90a7-6ddbebd992c0.jpg)
